# Generated by Django 3.2.8 on 2021-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_details',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register_details',
            name='Zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='register_details',
            table='register',
        ),
    ]
