# Generated by Django 3.2.8 on 2021-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pan_card', models.ImageField(height_field=300, upload_to='profiles', width_field=342)),
            ],
        ),
    ]
